# Generated by Django 6.0.4 on 2026-04-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_lat", models.DecimalField(decimal_places=5, max_digits=8)),
                ("origin_lng", models.DecimalField(decimal_places=5, max_digits=8)),
                ("dest_lat", models.DecimalField(decimal_places=5, max_digits=8)),
                ("dest_lng", models.DecimalField(decimal_places=5, max_digits=8)),
                (
                    "travel_mode",
                    models.CharField(
                        choices=[("WALK", "Walk"), ("TRANSIT", "Transit")],
                        max_length=16,
                    ),
                ),
                ("polyline", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=[
                            "origin_lat",
                            "origin_lng",
                            "dest_lat",
                            "dest_lng",
                            "travel_mode",
                        ],
                        name="routes_rout_origin__e437f0_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "origin_lat",
                            "origin_lng",
                            "dest_lat",
                            "dest_lng",
                            "travel_mode",
                        ),
                        name="routecache_unique_segment",
                    )
                ],
            },
        ),
    ]
