# Generated by Django 6.0.4 on 2026-04-23 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_id", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=300)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("poi_type", models.CharField(blank=True, max_length=100)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("lng", models.DecimalField(decimal_places=7, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="trip.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "place_id"),
                        name="bookmark_unique_place_per_trip",
                    )
                ],
            },
        ),
    ]
