# Generated by Django 6.0.4 on 2026-04-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0002_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="group_names",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
