# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0003_day_group_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="map_camera",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
