# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0004_trip_map_camera"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="ui_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
