# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0005_trip_ui_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="shape_vertices",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="location",
            name="entry_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="entry_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="exit_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="exit_lng",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
