# Generated by Codex on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0006_location_area_shape"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="transit_role",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
