# Generated by Django 6.0.4 on 2026-04-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0007_location_transit_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookmark",
            name="bookmark_unique_place_per_trip",
        ),
        migrations.AlterField(
            model_name="location",
            name="end_time",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="location",
            name="group_id",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="location",
            name="transit_role",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
